# ------------ Customizing static analysis ------------ #
#                          ---                          #
#   https://dart.dev/guides/language/analysis-options   #
# ----------------------------------------------------- #

linter:
  rules:
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_double_and_int_checks: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    avoid_returning_this: true
    avoid_unused_constructor_parameters: true
    cascade_invocations: true
    prefer_foreach: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true

analyzer:
  exclude:
    # Exclude from static analysis files that contain generated code
    - lib/data/**/*.g.dart
    - lib/services/**/*.g.dart
    - lib/generated_plugin_registrant.dart
    - lib/localUrl.dart
    - test/integration_test/integration_test.mocks.dart
    - test/view/execution/execution/widget/scan_ticket_modal_test.mocks.dart
  errors:
    todo: ignore
