name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate .env file
        run: |
          echo "ENV=production" > .env    

      - name: Generate index file
        run: |
          echo ${{ secrets.INDEX_HTML }} > /web/index.html 

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --no-tree-shake-icons

      - name: Deploy to OVH via FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get install -y lftp
          lftp -e "set ftp:ssl-allow no; mirror -R ./build/web ./www; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER